version: '3'
services:
  control:
    build:
      context: ./control
      dockerfile: Dockerfile
    container_name: control-node
    volumes:
       - ./control/files/ansible:/etc/ansible
    hostname: controlnode.demo.com
    networks:
      ansible-net:
        ipv4_address: 172.90.0.2
    extra_hosts:
      - 'managedubuntu.demo.com:172.90.0.3'
      - 'managedcentos.demo.com:172.90.0.4'

  managed-ubuntu:
    build:
      context: ./managed-ubuntu
      dockerfile: Dockerfile
    container_name: managed-ubuntu-node
    hostname: managedubuntu.demo.com
    networks:
      ansible-net:
        ipv4_address: 172.90.0.3
    extra_hosts:
      - 'controlnode.demo.com:172.90.0.2'
    depends_on:
      - control

  managed-centos:
    build:
      context: ./managed-centos
      dockerfile: Dockerfile
    container_name: managed-centos-node
    hostname: managedcentos.demo.com
    networks:
      ansible-net:
        ipv4_address: 172.90.0.4
    extra_hosts:
      - 'controlnode.demo.com:172.90.0.2'
    depends_on:
      - control

networks:
  ansible-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.90.0.0/24
